
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_kafka_app_db
    username: kafka_user_app
    password: password



  kafka:
    producer:
      bootstrap-address: localhost:9092